version: '2'
volumes:
    mariadb:
        external: true
services:
    mariadb:
        container_name: mariadb
        image: mariadb:latest
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        volumes:
            - mariadb:/var/lib/mysql
        restart: always
    lnmp:
        container_name: lnmp
        image: daocloud.io/wangyan/docker-lemp:latest
        ports:
            - "80:80"
            - "443:443"
        links:
            - mariadb
        volumes:
            - /var/www/html:/var/www/html
        restart: always